'use client';

import React, { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import ArgumentMapViewer from '@/components/argument-map/ArgumentMapViewer';

export default function ConversationArgumentMapPage() {
  const params = useParams();
  const router = useRouter();
  const conversationId = params.id as string;

  const [mapData, setMapData] = useState<any>(null);
  const [digest, setDigest] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const [mapRes, digestRes] = await Promise.all([
          fetch(`/api/conversations/${conversationId}/map`),
          fetch(`/api/conversations/${conversationId}/digest`),
        ]);

        if (mapRes.ok) {
          const mJson = await mapRes.json();
          setMapData(mJson.map?.data);
        }

        if (digestRes.ok) {
          const dJson = await digestRes.json();
          setDigest(dJson.digest);
        }
      } catch (err) {
        console.error('Failed to load argument map data:', err);
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, [conversationId]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-950 text-white flex items-center justify-center p-6">
        <div className="animate-pulse text-indigo-400 font-medium text-lg">
          Extracting argument structure and synthesizing debate map...
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-950 text-white p-6 md:p-10 space-y-8">
      {/* Navigation Header */}
      <div className="flex items-center justify-between border-b border-gray-800 pb-4">
        <div>
          <h1 className="text-3xl font-extrabold text-white">
            Post-Chat AI Digest & Argument Map
          </h1>
          <p className="text-sm text-gray-400 mt-1">
            Structured analysis generated by Gemini 2.0 Flash
          </p>
        </div>

        <button
          onClick={() => router.push('/debates')}
          className="px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-xl text-sm font-semibold transition-all"
        >
          View All Debates
        </button>
      </div>

      {/* Summary Digest Card */}
      {digest && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 rounded-2xl bg-gray-900 border border-gray-800 space-y-3 md:col-span-2">
            <h3 className="text-xs uppercase tracking-wider font-bold text-indigo-400">
              3-Sentence Debate Digest
            </h3>
            <p className="text-gray-200 text-base leading-relaxed">
              {digest.summary}
            </p>
          </div>

          <div className="p-6 rounded-2xl bg-indigo-950/40 border border-indigo-800/50 space-y-3">
            <h3 className="text-xs uppercase tracking-wider font-bold text-indigo-300">
              Key Open Question
            </h3>
            <p className="text-indigo-100 text-sm font-medium italic">
              "{digest.unresolvedQuestion}"
            </p>
          </div>
        </div>
      )}

      {/* React Flow Interactive Argument Map */}
      <div>
        {mapData ? (
          <ArgumentMapViewer data={mapData} />
        ) : (
          <div className="p-12 text-center bg-gray-900 rounded-2xl border border-gray-800 text-gray-400">
            No argument map graph available for this conversation yet.
          </div>
        )}
      </div>
    </div>
  );
}
